name: Build, Scan and Deploy to Amazon ECS

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch

jobs:
  # Job: Build Docker image, scan for vulnerabilities, and push to Amazon ECR
  build-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-3

      # Step 3: Authenticate with Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Step 4: Set up Docker buildx and Build, tag, and push the image to Amazon ECR
      - name: Set up Docker buildx and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: latest
          GITHUB_SHA: ${{ github.sha }}  # Git commit hash for versioning
        run: |
          # Set up buildx
          docker buildx create --use
          
          # Build and push 'latest' tag for linux/amd64 platform
          docker buildx build --platform linux/amd64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f .devops/Dockerfile --push .
          
          # Build and push short Git commit SHA tag for linux/amd64 platform
          VERSION_TAG="${GITHUB_SHA:0:7}"  # Short SHA (first 7 characters)
          docker buildx build --platform linux/amd64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION_TAG -f .devops/Dockerfile --push .

      # Step 5: Run Trivy vulnerability scanner on the Docker image and generate table report
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: '${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:latest'
          format: 'table'  # Use table format for vulnerabilities
          exit-code: '1'  # Exit with error if vulnerabilities are found
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'
          output: 'trivy-report.json'  # Output to a JSON file instead of HTML

      # Step 6: Upload Trivy JSON report as artifact
      - name: Upload Trivy JSON report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: trivy-vulnerability-report
          path: trivy-report.json

  # Job: Update ECS task definition and deploy
  deploy:
    runs-on: ubuntu-latest
    needs: build-scan  # This job depends on the build-scan job

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-3

      # Step 3: Download the current task definition from Amazon ECS
      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition erp-be-development --query "taskDefinition" > task-definition.json

      # Step 4: Update the task definition with the new image
      - name: Fill in new image ID in task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: erp-be-development
          image: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:latest

      # Step 5: Deploy the updated task definition to ECS
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: erp-be-development
          cluster: studilmu-development-cluster
